#!/bin/env bash

#Check if run as root
if [ "$UID" -ne 0 ] ; then
	echo "Run again as sudo!"
	exit 1
fi

echo "Stopping hostapd..."
systemctl stop hostapd

echo "Restoring interfaces to default"
cp default-interfaces /etc/network/interfaces

echo "Delete br0 interface"
ip link delete br0

echo "Restart networking releated services..."
systemctl stop networking 
systemctl start hostapd
systemctl start networking

echo "Modifying kernel routes..."
route add default gw 192.168.1.1 eth0

echo "Some bridge control commands to check the status:"
brctl show
brctl showstp br0
